### ISSUE TITLE
Revisión INSTAGRAM FEED CON BOOTSTRAP

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/FernandoSformulario#1]
# Revisión - Hacen falta correcciones ⚠️

## Feedback
- Buen trabajo @FernandoSSantana  , pero hay que corregir algunas cosillas

## Mejores prácticas/comentarios
- En el campo "Pick a state" no hay opciones disponibles

**Comment by FernandoSSantana** [comment]
Que lio me has hecho! ajajajaj
No entendia cual era el "pick a state" en el post de instagram  ajajajaj
Ya esta arreglado. Gracias Edo

**Comment by EduardoHernandezGuzman** [comment]
Me equivoqué poniendo el título, jajaja... Es el formulario... perdón por el lío.

**Comment by EduardoHernandezGuzman** [comment]
Muy bien con las correcciones!!! Muy buen trabajo!!!
